# Generated by Django 3.0.4 on 2020-08-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_url', models.URLField()),
                ('shorted_url', models.URLField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
