# Generated by Django 3.0.4 on 2020-08-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20200820_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='openurls',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
